#version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      #dockerfile: Dockerfile
    #container_name: resept-app-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: devdb
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    
volumes:
  dev-db-data: